name: Build and Release with Maven

on:
  push:
    tags:
      - "*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload build artifact
        run: |
          mv ${{ github.workspace }}/missilewars/target/missilewars*.jar MissileWars-${{ github.ref_name }}.jar

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: MissileWars-${{ github.ref_name }}.jar
